### ISSUE TITLE
Hi :)

### ISSUE THREAD

**Issue by mr21** [rsimmons/fastidious-envelope-generator#1]
Do you have time to participate on the @GridSound project?
It will be a DAW in HTML5,  and we will need an audio envelope too (obviously).
We'll write the CSS components to edit the envelope etc. it's a long project.

Your code seems really good, but maybe we can rewrite it to minify it a lot more, we'll not need any test like `typeof value === 'number'`, because this code will be used by another code, not directly with some `<input/>` user to check.

Anyway, tell me if I can invite you on our slack :)

**Comment by rsimmons** [comment]
Hi! Thanks for your invite. I'm currently busy working on a related project, not a DAW exactly but a browser-based Eurorack-style modular synth, so I want to focus on that. Also the traditional DAW structure doesn't interest me very much these days anyways.

I think it makes sense to keep the parameter validation in Fastidious to help catch bugs with a variety of callers, but it shouldn't be hard to maintain a fork if you want to whittle it down.

I think that the Web Audio space could greatly benefit from some component standards, comparable to VST/AU. This might be a common point of interest, let me know if you want to discuss.

**Comment by mr21** [comment]
We will clearly need some effects anyway. We are seeing how to generate some sound with `oscillatorNode`s etc. I don't know if there is any standard, it's looks like everybody create his own standard you know...

But I've start a rewrite of our codebase, and now, it's separated into 4 different repos, so if we continue the same project (a complete DAW) we'll can think about some standard audio components.

I was wondering about the type checking to have the minimal code, but yes the debug is more difficult after that maybe...
